import { Role, MailboxStatus, LeadStatus, CampaignStatus, EmailDispatchStatus } from "@prisma/client";

export interface MockUser {
  id: string;
  email: string;
  name: string;
  isSuperAdmin: boolean;
  role: Role;
  organizationId: string;
  organizationName: string;
  planName: string;
}

export const MOCK_USERS: Record<string, MockUser> = {
  "admin@zoqonyx.com": {
    id: "user_admin_01",
    email: "admin@zoqonyx.com",
    name: "Zawar Ahmed (Super Admin)",
    isSuperAdmin: true,
    role: Role.OWNER,
    organizationId: "org_super_01",
    organizationName: "Nawix Platform Administration",
    planName: "ENTERPRISE",
  },
  "owner@navixdemo.com": {
    id: "user_owner_01",
    email: "owner@navixdemo.com",
    name: "Alex Vance (Founder & Owner)",
    isSuperAdmin: false,
    role: Role.OWNER,
    organizationId: "org_navix_01",
    organizationName: "Navix Demo Solutions",
    planName: "PRO",
  },
  "admin@navixdemo.com": {
    id: "user_admin_org_01",
    email: "admin@navixdemo.com",
    name: "Sarah Chen (Org Admin)",
    isSuperAdmin: false,
    role: Role.ADMIN,
    organizationId: "org_navix_01",
    organizationName: "Navix Demo Solutions",
    planName: "PRO",
  },
  "manager@navixdemo.com": {
    id: "user_manager_01",
    email: "manager@navixdemo.com",
    name: "Marcus Miller (Campaign Manager)",
    isSuperAdmin: false,
    role: Role.MANAGER,
    organizationId: "org_navix_01",
    organizationName: "Navix Demo Solutions",
    planName: "PRO",
  },
  "member@navixdemo.com": {
    id: "user_member_01",
    email: "member@navixdemo.com",
    name: "Elena Rostova (SDR Outreach Specialist)",
    isSuperAdmin: false,
    role: Role.MEMBER,
    organizationId: "org_navix_01",
    organizationName: "Navix Demo Solutions",
    planName: "PRO",
  },
};

export const MOCK_MAILBOXES = [
  {
    id: "mbx_demo_01",
    organizationId: "org_navix_01",
    email: "outreach@navixdemo.com",
    fromName: "Alex Vance | Navix Solutions",
    providerType: "SMTP_IMAP",
    status: MailboxStatus.ACTIVE,
    dailyLimit: 250,
    sentToday: 42,
    spfStatus: "VALID",
    dkimStatus: "VALID",
    dmarcStatus: "VALID",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mbx_demo_02",
    organizationId: "org_navix_01",
    email: "growth@newixtechsolutions.com",
    fromName: "Navix Growth Team",
    providerType: "MAILGUN",
    status: MailboxStatus.ACTIVE,
    dailyLimit: 500,
    sentToday: 118,
    spfStatus: "VALID",
    dkimStatus: "VALID",
    dmarcStatus: "VALID",
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_CAMPAIGNS = [
  {
    id: "cmp_demo_01",
    organizationId: "org_navix_01",
    name: "US Medical Clinics – AI Automation & Web Systems",
    description: "Multi-touch outbound cadence targeting clinic directors and practice administrators.",
    status: CampaignStatus.RUNNING,
    dailyLimit: 150,
    timezone: "America/New_York",
    startHour: 9,
    endHour: 17,
    isTestMode: false,
    mailbox: MOCK_MAILBOXES[0],
    sequenceSteps: [
      {
        id: "step_01",
        stepNumber: 1,
        waitDays: 0,
        subject: "Modernizing Patient Experience for {{company_name | fallback:'your clinic'}}",
        bodyHtml: "<p>Hi {{first_name | fallback:'there'}},</p><p>I noticed {{company_name}} is expanding healthcare services in {{city | fallback:'your area'}}.</p><p>We recently built an automated booking and patient follow-up engine for specialized medical clinics that increased show rates by 34%.</p><p>Would you be open to a brief 7-minute visual breakdown of how this works?</p><p>Best regards,<br/>Alex Vance</p>",
      },
      {
        id: "step_02",
        stepNumber: 2,
        waitDays: 3,
        subject: "Quick follow-up regarding {{company_name}} patient workflow",
        bodyHtml: "<p>Hi {{first_name}},</p><p>Following up on my previous note. We put together a short video case study demonstrating the exact patient intake pipeline.</p><p>Are you available this Thursday at 2 PM EST for a quick look?</p>",
      },
      {
        id: "step_03",
        stepNumber: 3,
        waitDays: 4,
        subject: "Final thought for {{company_name}}",
        bodyHtml: "<p>Hi {{first_name}},</p><p>If patient intake optimization is not on your priority list this quarter, no problem at all. I will not follow up further.</p><p>Wishing {{company_name}} continued success!</p>",
      },
    ],
    _count: {
      campaignLeads: 148,
      sentEmails: 384,
      scheduledEmails: 52,
    },
    analytics: {
      totalLeads: 148,
      sentCount: 384,
      repliedCount: 29,
      bouncedCount: 4,
      unsubscribedCount: 2,
      scheduledCount: 52,
      replyRate: "7.6%",
      bounceRate: "1.0%",
    },
  },
  {
    id: "cmp_demo_02",
    organizationId: "org_navix_01",
    name: "Enterprise B2B SaaS Outreach – Q4 Expansion",
    description: "Targeting VP of Engineering & Operations at Series A-C startups.",
    status: CampaignStatus.READY,
    dailyLimit: 200,
    timezone: "UTC",
    startHour: 9,
    endHour: 18,
    isTestMode: false,
    mailbox: MOCK_MAILBOXES[1],
    sequenceSteps: [
      {
        id: "step_saas_01",
        stepNumber: 1,
        waitDays: 0,
        subject: "Infrastructure scalability question for {{company_name}}",
        bodyHtml: "<p>Hi {{first_name}},</p><p>Loved your recent product announcement at {{company_name}}. We build high-throughput email and messaging pipelines for fast-scaling engineering teams.</p>",
      },
    ],
    _count: {
      campaignLeads: 85,
      sentEmails: 0,
      scheduledEmails: 85,
    },
    analytics: {
      totalLeads: 85,
      sentCount: 0,
      repliedCount: 0,
      bouncedCount: 0,
      unsubscribedCount: 0,
      scheduledCount: 85,
      replyRate: "0.0%",
      bounceRate: "0.0%",
    },
  },
];

export const MOCK_LEADS = [
  {
    id: "lead_01",
    organizationId: "org_navix_01",
    email: "dr.sarah.jenkins@metrohealthclinic.com",
    firstName: "Sarah",
    lastName: "Jenkins",
    company: "Metro Health Specialist Clinic",
    jobTitle: "Medical Director",
    industry: "Healthcare",
    city: "Chicago",
    country: "United States",
    status: LeadStatus.REPLIED,
    tags: ["High Priority", "Verified", "Medical"],
    createdAt: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
  },
  {
    id: "lead_02",
    organizationId: "org_navix_01",
    email: "david.miller@apexhealthcare.io",
    firstName: "David",
    lastName: "Miller",
    company: "Apex Healthcare Innovations",
    jobTitle: "Chief Executive Officer",
    industry: "HealthTech",
    city: "Austin",
    country: "United States",
    status: LeadStatus.INTERESTED,
    tags: ["Decision Maker", "Demo Scheduled"],
    createdAt: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
  },
  {
    id: "lead_03",
    organizationId: "org_navix_01",
    email: "rachel.zhao@bioveritaslabs.com",
    firstName: "Rachel",
    lastName: "Zhao",
    company: "BioVeritas Clinical Diagnostics",
    jobTitle: "VP Clinical Operations",
    industry: "Diagnostics",
    city: "Boston",
    country: "United States",
    status: LeadStatus.CONTACTED,
    tags: ["In Sequence (Step 2)"],
    createdAt: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
  },
  {
    id: "lead_04",
    organizationId: "org_navix_01",
    email: "marcus.vance@horizonphysicians.org",
    firstName: "Marcus",
    lastName: "Vance",
    company: "Horizon Physicians Group",
    jobTitle: "Practice Administrator",
    industry: "Medical",
    city: "Seattle",
    country: "United States",
    status: LeadStatus.ACTIVE,
    tags: ["Outreach Active"],
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: "lead_05",
    organizationId: "org_navix_01",
    email: "karen.lindqvist@nordicwellness.com",
    firstName: "Karen",
    lastName: "Lindqvist",
    company: "Nordic Wellness Clinics",
    jobTitle: "Head of Patient Experience",
    industry: "Wellness",
    city: "New York",
    country: "United States",
    status: LeadStatus.NEW,
    tags: ["CSV Ingestion"],
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: "conv_demo_01",
    organizationId: "org_navix_01",
    campaignId: "cmp_demo_01",
    leadId: "lead_01",
    mailboxId: "mbx_demo_01",
    status: "REPLIED",
    subject: "Re: Modernizing Patient Experience for Metro Health Specialist Clinic",
    snippet: "Hi Alex, thanks for reaching out. Yes, we are actively looking into patient follow-up automation. Can you send over a deck or quick 15-min calendar link?",
    lead: MOCK_LEADS[0],
    campaign: { name: "US Medical Clinics – AI Automation" },
    mailbox: { email: "outreach@navixdemo.com" },
    messages: [
      {
        id: "msg_01",
        direction: "OUTBOUND",
        fromEmail: "outreach@navixdemo.com",
        toEmail: "dr.sarah.jenkins@metrohealthclinic.com",
        subject: "Modernizing Patient Experience for Metro Health Specialist Clinic",
        bodyText: "Hi Sarah,\n\nI noticed Metro Health is expanding healthcare services in Chicago.\nWe recently built an automated booking engine that increased show rates by 34%.\n\nWould you be open to a brief 7-minute visual breakdown of how this works?\n\nBest regards,\nAlex Vance",
        createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
      },
      {
        id: "msg_02",
        direction: "INBOUND",
        fromEmail: "dr.sarah.jenkins@metrohealthclinic.com",
        toEmail: "outreach@navixdemo.com",
        subject: "Re: Modernizing Patient Experience for Metro Health Specialist Clinic",
        bodyText: "Hi Alex, thanks for reaching out. Yes, we are actively looking into patient follow-up automation. Can you send over a deck or quick 15-min calendar link?\n\nDr. Sarah Jenkins\nMetro Health Specialist Clinic",
        createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
      },
    ],
  },
];
